### PR TITLE
Byte order marks cause unit test failures with Java 1.8

### PR DESCRIPTION
**Pull request by swsch**
I stumbled on this while looking for something else.

Also: MustangReaderWriterTest.java references a resource `/MustangGnuaccountingBeispielRE-20190610_507blanko.pdf`, which is not in the repository.

### CODE REVIEW

**Comment by jstaerk** [comment]
I agree to the first change, thanks, but I would prefer to leave the BOM in the test case for custom XML because that is a) valid and b) a test if it is later removed and parsed correctly

**Comment by swsch** [comment]
A BOM makes sense for byte oriented things like input streams or byte arrays. A string as a sequence of chars already is encoded and hence BOMs are not required. At least that's my understanding.

So if that test used a `byte[]`, including BOMs would be a great idea.

With the BOM, the unit test complains about it:
```
testCustomZF2Export(org.mustangproject.ZUGFeRD.MustangReaderWriterCustomXMLTest)  Time elapsed: 0.097 sec  <<< ERROR!
org.mustangproject.ZUGFeRD.ZUGFeRDExportException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extractString(ZUGFeRDImporter.java:200)
```

**Comment by jstaerk** [comment]
the bom does (in the beginning of an XML file) does appear in the wild (see corpus, e.g. some french official examples) and i want that testet. Anyway I might add another test.

**Comment by swsch** [comment]
oh dear ... I expected too much of the java input stream handling implementation, my bad. The BOM is not discarded but turns up as first codepoint in the string, which then needs to be discarded before the XML parser gets its hand on the data.

**Pull request merged**
